# Generated by Django 4.1 on 2022-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_week",
                    models.CharField(
                        choices=[
                            ("SEC", "Segunda-feira"),
                            ("TER", "Terça-feira"),
                            ("QUA", "Quarta-feira"),
                            ("QUI", "Quinta-feira"),
                            ("SEX", "Sexta-feira"),
                            ("SAB", "Sabado-feira"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "time_class",
                    models.CharField(
                        choices=[("A", "A"), ("B", "A"), ("C", "A"), ("D", "A")],
                        max_length=1,
                    ),
                ),
                (
                    "class_shift",
                    models.CharField(
                        choices=[("MNH", "Manhã"), ("TRD", "Tarde"), ("NT", "Noite")],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.CharField(max_length=2)),
                ("number", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(default="This is void", max_length=300),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "class_hours",
                    models.ManyToManyField(
                        related_name="subject", to="ults.classhours"
                    ),
                ),
                (
                    "classroom",
                    models.ManyToManyField(related_name="subject", to="ults.classroom"),
                ),
            ],
        ),
    ]
