# Generated by Django 4.1 on 2022-09-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ults", "0002_alter_classhours_time_class"),
        ("ults", "0002_course_alter_classhours_time_class"),
    ]

    operations = []
