# Generated by Django 4.1 on 2022-09-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ults", "0003_merge_20220930_1949"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
