# Generated by Django 4.1 on 2022-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ults", "0004_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
