# Generated by Django 4.1 on 2022-10-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0009_student_registration"),
        ("ults", "0005_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="coordenador",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="entities.teacher",
            ),
        ),
    ]
