# Generated by Django 4.1 on 2022-11-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ults", "0006_course_coordenador"),
        ("ults", "0006_subject_teacher"),
    ]

    operations = []
