# Generated by Django 4.1 on 2022-09-28 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
