# Generated by Django 4.1 on 2022-09-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_student_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entities.student",
                    ),
                ),
            ],
        ),
    ]
