# Generated by Django 4.1 on 2022-09-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0004_egress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="create_date",
            new_name="timestemp",
        ),
    ]
