# Generated by Django 4.1 on 2022-09-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0005_rename_create_date_student_timestemp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="timestemp",
        ),
        migrations.DeleteModel(
            name="Egress",
        ),
    ]
