# Generated by Django 4.1 on 2022-09-30 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0006_remove_student_timestemp_delete_egress"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
