# Generated by Django 4.1 on 2022-10-01 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0008_teacher_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="registration",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
